name: API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering with run mode
    inputs:
      run_mode:
        description: 'Test execution mode'
        required: false
        default: 'quick'
        type: choice
        options:
          - quick
          - full

# Cancel in-progress runs to avoid resource conflicts
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Start demo app container
      run: |
        docker run -d -p 3100:3100 --name demo-app automaticbytes/demo-app:latest
        # Wait for API to be ready with longer timeout for ARM64 emulation
        timeout 60 bash -c 'until curl -f http://localhost:3100/api; do sleep 3; done'
        
    - name: Run API tests (Quick mode)
      if: ${{ github.event.inputs.run_mode == 'quick' || github.event.inputs.run_mode == '' }}
      run: mvn test -Dtest=InventoryTestRunner -Dkarate.options="--tags @smoke"

    - name: Run API tests (Full mode)
      if: ${{ github.event.inputs.run_mode == 'full' }}
      run: mvn test -Dtest=InventoryTestRunner
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: surefire-reports
        path: target/surefire-reports/
        retention-days: 30
        
    - name: Upload Karate reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: karate-reports
        path: target/karate-reports/
        retention-days: 30
        
    - name: Cleanup demo app
      if: always()
      run: |
        docker stop demo-app || true
        docker rm demo-app || true